### ISSUE TITLE
Create Account Controller

### ISSUE THREAD

**Issue by yehandesilva** [yehandesilva/monkeyPoll#19]
Create a REST controller to handle account routes. 
Routes include:
- POST account
- GET account
- PATCH account? (If users should be able to change account details)
- DELETE account? (If users should be allowed to delete their accounts)

Take a look at the [response codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) to ensure the right code is being returned.

**Comment by AminZeina** [comment]
I think that for our initial prototype, we should only have endpoints to create a new account and to log into an account.

updating and deleting an account are both great ideas for features which we should add before the final deliverable, but I'm thinking we should wait on it for now as we would need to add frontend interfaces for updating and deleting as well. I think we should first spend the time on the core features like interfaces and endpoints to create surveys and then circle back to this for milestone 3. Thoughts?

**Comment by yehandesilva** [comment]
No that makes sense, creating and signing in users should be our main priority for getting a working use case done for our Early Prototype milestone.

**Comment by AminZeina** [comment]
This issue is blocked by #30 as we need an authentication mechanism to be able to create login endpoints.

**Comment by AminZeina** [comment]
Implementations for `/login` and `/register` are mostly complete in commit https://github.com/yehandesilva/monkeyPoll/commit/9c0d33ac16d37c2bbc35ac5216fd16adb9719b89 (branch); they aren't functional yet but the interface is defined so we should be good to start working on #20 and the frontend functionality.

@all If we need more endpoints than this for the early prototype, post them here. We also may have to adjust what data is being returned by these endpoints depending on what we need to do with them on the frontend

**Comment by AminZeina** [comment]
After a team discussion, the `/login` should return a JSON representation of the Account if a login is successful. `register` should also return a valid JSON
