### ISSUE TITLE
Create Project Logos

### ISSUE THREAD

**Issue by yehandesilva** [yehandesilva/monkeyPoll#22]
We need a project logo that we can display on the welcome screen as well within the app itself. Also need to use the logo as a favicon.

**Comment by pathumd** [comment]
Logo files are attached below.

<img width="1349" alt="full-logo" src="https://github.com/user-attachments/assets/785b7b89-f7be-451f-a760-b2c95f87ff7f">
<img width="323" alt="monkey-head" src="https://github.com/user-attachments/assets/9d8a84a0-89ed-440c-bdc8-02001647a117">
<img width="944" alt="text-logo" src="https://github.com/user-attachments/assets/5ae1ea0e-ed9f-49a7-a888-57e2e4f03e7d">

**Comment by yehandesilva** [comment]
I added the logos to the fronend, but just inverted the colors. Went with a dark background so our logo will be in white. The background color I decided to go with is #014F5E.

![image](https://github.com/user-attachments/assets/9d1d8fbf-ae27-4e26-bba7-9209cc9399a1)

I noticed the images were a bit blurry, especially blown up on a larger screen. Could you generate new logos in SVG format instead of PNG?
The new logo will then need to be placed:
- On welcome screen
- On login dialog
- Favicon

**Comment by pathumd** [comment]
A new logo was created to provide a more modern, flat, and minimal design. As requested, the text-based logo and standalone logo (monkey head) is in SVG format, allowing the logo to appear more crisp when downscaling or upscaling. An all-white version and a green-black version of the logos (in SVG format), as well as a favicon (in PNG format that is resized to 32x32 pixels) have been attached below:
![full-logo-black](https://github.com/user-attachments/assets/54d3586b-b0ee-4f90-954e-0f55923690c6)
![monkey-logo-green](https://github.com/user-attachments/assets/821d83e2-448e-41b0-ac78-7a4390a9ab1a)
![full-logo-white](https://github.com/user-attachments/assets/f9e3a5dd-ae91-4503-b230-89936ef1cf4e)
![monkey-logo-white](https://github.com/user-attachments/assets/2000e5f4-6138-4fec-a3d6-bf746e76afc6)
![favicon](https://github.com/user-attachments/assets/f5d7fc36-a399-46cb-a78d-2604504efbf7)

**Comment by yehandesilva** [comment]
Looks great! Like the new logos better than the previous.
