### ISSUE TITLE
Integrate Frontend with pom.xml 

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#28]
As stated in the project requirements, we should have a single pom.xml that can be used to build and run our entire application, so we need to integrate our frontend into a single build using the pom.xml.

**Comment by yehandesilva** [comment]
Going to change this to finish on our early prototype as the pom file being able to build our project is one of requirements stated.

**Comment by MichaelKyrollos** [comment]
Perfect, I'll pick up this task

**Comment by AminZeina** [comment]
> Going to change this to finish on our early prototype as the pom file being able to build our project is one of requirements stated.

Oh my mistake I got confused with the ordering... I thought Alpha Release was the first milestone. Definitely should have been marked as early prototype. Thanks for noticing and fixing that!
