### ISSUE TITLE
Run 'mvn spring-boot:run' from the root

### ISSUE THREAD

**Issue by MichaelKyrollos** [yehandesilva/monkeyPoll#36]
**Issue Description:**

This issue is based on [PR #35](https://github.com/yehandesilva/monkeyPoll/pull/35). The changes to the `pom.xml` file now allow you to run `mvn clean install` from the root directory.

However, it would be beneficial to enable running `mvn spring-boot:run` directly from the root directory without navigating to the backend directory.

**Current Issue:**

When attempting to run `mvn spring-boot:run` from the root, the following error is encountered:

```
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\.......\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

**Comment by yehandesilva** [comment]
Has this been resolved?

**Comment by AminZeina** [comment]
I think so, @MichaelKyrollos could you confirm?

**Comment by MichaelKyrollos** [comment]
Yeah we are not going to do it since with the new vite changes, it helps run things

**Comment by MichaelKyrollos** [comment]
Yeah we are not going to do it since with the new vite changes, it helps run things
