### ISSUE TITLE
Create Entity classes for Survey

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#40]
We need to create an Entity class for a survey which contains a collection of survey `Questions` and likely also a collection of `Question Responses`. This issue is blocked by #39 . 

A logged in user (i.e. an `Account` entity) can create Surveys, so we need to link each survey to an Account - this requires additions to `Account`. More details are discussed in #16.

**Comment by yehandesilva** [comment]
I needed this entity to be created in order to create relating entities, therefore this issue has been completed with #55.
