### ISSUE TITLE
Create Post endpoint for Survey

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#41]
We need to create a Survey Controller with endpoints related to survey interactions. Specifically, at minimum, we would need:
- Create survey (authenticated) - allow a user to create a new survey
- Close survey (authenticated)  - allow the survey owner to close the survey (and return survey results?)
- Get survey results (authenticated) - allow the survey owner to see the results of the survey
- Get survey (un-authenticated) - allow anyone to fill in a given survey
- Send survey results (un-authenticated) - allow anyone to submit their response to a survey

We'll have to add these endpoints to `SecurityConfig.java` with their respective permissions.

This is blocked by #40

**Comment by yehandesilva** [comment]
We'll also need a request to POST a survey response.

**Comment by AminZeina** [comment]
Right, missed that thanks. Updated the issue
