### ISSUE TITLE
Add interface for creating a Survey

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#42]
We need to have a page for the user to create a survey. The page should likely be a form where the user can add a list of different question types, and then eventually POST the survey to the relevant Survey Controller endpoint defined in #41 . 

This page should only be available to authenticated users, so the user will have to login to access it. There should be a button somewhere on the user's home page (after log in) that loads this form.

**Comment by AminZeina** [comment]
Here's a rough diagram of what I'm planning for the survey creation page, let me know if you have any suggestions!

![CreateSurveyMockup](https://github.com/user-attachments/assets/356dab61-efaa-441c-89d2-4715395000a6)

**Comment by yehandesilva** [comment]
Looks good. The components that are required for this structure would be <Button/> for all the buttons, <InputText/> to enter text and <Dropdown/> which gives a selection of options. More documentation can be found here #24. You will also need to consider <InputNumber/> which is used to enter numerical min/max values for numerical questions (The component has built in min/max props) and components to display options for choice questions.

**Comment by AminZeina** [comment]
Oh that's a great point. having to select the range/options for a response completely slipped my mind; thanks for pointing that out! I'll implement those selections using the same design above by dynamically adding more input fields once the user selects the question type.
