### ISSUE TITLE
Add interface for responding to a Survey

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#43]
We need to have a page for users to fill in created surveys. Any user should be able to enter a survey ID (or some reference/code/etc.) which will then render the requested survey. This should give the user a form that they can fill in with all the questions of the requested survey, and then eventually submit their response with a POST to the relevant Survey Controller endpoint defined in #41 .

As mentioned, any user should be able to fill in a survey, thus users should be able to load a survey from the public welcome page.

**Comment by pathumd** [comment]
![survey-response-design](https://github.com/user-attachments/assets/aa9a039c-45b5-4e5a-a1af-3f5354136e45)

The image above is a rough sketch of what I'm planning to make the UI for responding to a survey look like. There will be no pagination (i.e. all the questions in the survey will appear on a single page to reduce the amount of clicking for the user) and the following will be the PrimeReact components I'm thinking of using for each question type:

Text Question: InputTextArea (https://primereact.org/inputtextarea/)
Number Question: Knob (https://primereact.org/knob/)
Choice Question: Dynamically created RadioButtons (https://primereact.org/radiobutton/)

**Comment by pathumd** [comment]
Additional note: There will be a 'Submit' button below the last question of the survey.
