### ISSUE TITLE
Create Alpha Release Diagrams 

### ISSUE THREAD

**Issue by yehandesilva** [yehandesilva/monkeyPoll#47]
Create Model UML class diagrams and database schema for our alpha release. This should be the complete representation of our project as no new fields or classes should be added in the next releases.

**Comment by yehandesilva** [comment]
@MichaelKyrollos can you share the diagram file you created for the early prototype release? Like if you created the diagrams in diagrams.net so I can expand on that for the new diagrams.

**Comment by MichaelKyrollos** [comment]
> @MichaelKyrollos can you share the diagram file you created for the early prototype release? Like if you created the diagrams in diagrams.net so I can expand on that for the new diagrams.

Here you go @yehandesilva [Diagram.net ](https://drive.google.com/file/d/1xvhAThpnwUjfmz7hT5Y4z0z5fZBkMcum/view?usp=sharing)

**Comment by yehandesilva** [comment]
Perfect.
