### ISSUE TITLE
Create JUnit tests to verify Entity persistence

### ISSUE THREAD

**Issue by pathumd** [yehandesilva/monkeyPoll#6]
Create JUnit test cases to ensure that all entities are properly persisted, the expected fields are persisted for each entity, and relationships are correct and functional.

**Comment by yehandesilva** [comment]
Closing this issue as it is too generic. It is composend of many sub issues which are better to treat individually to allow for better issue tracking and assignment. Ideally, after the JUnit tests should be the final step of each entity implementation and should not be an issue we address at the very end.
