### ISSUE TITLE
Add back button on Survey Page

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#69]
Currently there is no way to return to the home screen when on the survey page (i.e., when creating a survey). The only available actions are submit and login. We should add a back button to allow the user to "cancel" filling in the survey and return home

**Comment by yehandesilva** [comment]
I was able to finish this in #73. I kept getting stuck, causing me to need to refresh and sign back in. So I just added the small fix to complete this issue.
