### ISSUE TITLE
Implement circuit breaker pattern for AI api calls

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#75]
For our presentation topic, we need to implement the circuit breaker pattern. To do this, we need to create an endpoint that returns a list of response from a remote api call to Google Gemeni (this endpoint essentially acts as a wrapper around the Gemeni api). 

To ensure we can compare the before and after of using circuit breaker, we should first implement the endpoint without the pattern, then implement the pattern.

**Comment by AminZeina** [comment]
I believe this was completed last week, but we might still need to merge and deploy the branch, @pathumd or @MichaelKyrollos could you confirm?

**Comment by pathumd** [comment]
Yep the circuit breaker pattern was implemented in a separate branch, but was not merged yet. I'll merge that soon.
