### ISSUE TITLE
Develop Front-end

### ISSUE THREAD

**Issue by pathumd** [yehandesilva/monkeyPoll#8]
Developing the front-end includes creating a view where a user can create an account (to create and manage surveys), or sign-in to their existing account, a view to view and manage created surveys (dashboard), a view for creating a survey (i.e. adding and removing questions), a view for viewing survey results, and a view for filling in and submitting a view (displaying a survey).

**Comment by yehandesilva** [comment]
Closing this issue as it is too generic. It is composend of many sub issues which are better to treat individually to allow for better issue tracking and assignment.
